feat(tpp-snap): remove the bundled tpp-snap version and dynamically load specified version
e-Spirit/fsxa-pattern-library pull request #6
Opened 2021-02-26 10:41 UTC by tgolbs

You can now pass the version of the fs-tpp-api which should be used. This gives you more flexibility
to use new features, when the standard is not updated yet or helps you, when your server is running
an older version. If you do not specify a version the default will be 2.2.1 for now. If this
changes, we will inform you in our release notes.

2021-02-26 13:10 UTC, dbarczewski requested changes
Great work. Please edit that one line and we can merge this PR.

2021-02-26 13:13 UTC, ninoNato requested changes
Good job! Just one little thing to fix

2021-02-26 13:13 UTC, ninoNato commented on src/components/App.tsx
> +          const TPP_SNAP = getTPPSnap();
getTPPSnap() may return `null`, so we should check for that in order to prevent errors

2021-03-09 09:04 UTC, dbarczewski approved these changes
Great work!

2021-03-09 09:05 UTC, merged