fix(getters): incorrect content projection
e-Spirit/fsxa-pattern-library pull request #98
Opened 2022-10-25 10:47 UTC by lksmsr

2022-10-25 11:04 UTC, deangite requested changes

2022-10-25 11:04 UTC, deangite commented on src/utils/getters.ts
> +  if (getStoredItem($store, currentPath)) return;
please you curly brackets
```
const navigationData = $store.state.fsxa.navigation;

  if (!navigationData || !currentPath) {
    return;
  }

  const path = decodeURIComponent(currentPath || "");

  if (
    findNodeInSeoRouteMap(path, navigationData) ||
    getStoredItem($store, currentPath)
  ) {
    return;
  }
  ```

2022-10-25 11:04 UTC, deangite commented on src/utils/getters.ts
> +      await fetchDatasetIfMissing(
please change the name of function to `fetchMissingDataset`

2022-11-30 08:35 UTC, henczi-espirit requested changes
This PR contains an imcomplete implementation

2022-12-09 15:29 UTC, henczi-espirit commented
issue will be resolved by a different PR

2022-12-09 15:29 UTC, closed without merging